### ISSUE TITLE
Why aren't the render_file and render_with_layout 'locals' parameter used?

### ISSUE THREAD

**Issue by dpolivy** [pillarjs/hbs#102]
I've been debugging some other issues in the code, and am curious to understand why the `render_file` and `render_with_layout` functions are using the parent scope `options` object instead of the `locals` which is provided as a function parameter?

See [L54](https://github.com/donpark/hbs/blob/master/lib/hbs.js#L54) and [L84](https://github.com/donpark/hbs/blob/master/lib/hbs.js#L84).

As far as I can tell, these functions are called with the `options` parameter from the middleware function -- so it should be more performant to use the function parameter rather than try and use `options` from the parent scope, right?

**Comment by dougwilson** [comment]
Hi @dpolivy I've started to maintain this module and am going through the issues. It seems like in the time since this was made, the links above don't seem to really go to the original place, so I'm not 100% sure where you are looking.

And even then, I wouldn't unfortunately know enough (yet) to be able to answer why something was done the way it was.

I would suggest that if you're experiencing a bug feel free to make a pull request or even open an issue explaining the bug / how to reproduce it.

**Comment by dpolivy** [comment]
@dougwilson If you look at something prior to v3.1.0 the links should go to the right place. It looks like I fixed this in this PR/commit: https://github.com/pillarjs/hbs/commit/720395bb1e1a9c52e903190bd0800496365619de

Basically, there was a `var locals = options;` line in there that was extraneous, since `locals` was passed in as a parameter to the function already. It was a long time ago, but I think that's what this issue was about.
