### ISSUE TITLE
Cannot access request-level locals in recursive partials

### ISSUE THREAD

**Issue by kidlj** [pillarjs/hbs#133]
### Version
hbs@4.0.1 

### Description
request-level locals are accessible in normal partials, but can't be accessed in recursive partials.

In the example below, the local `requestId` shows nothing, which makes `"goto="`.

### item.hbs

```html
{{#if comments}}
  <ul>
    {{> list}}
  </ul>
{{/if}}
```

### list.hbs (recursive partial)
```html
{{#each comments}}
    <li>
      {{ text }}
      <a href="/reply?id={{ _id }}&goto={{ requestId }}">Reply</a>
      {{#if comments}}
        <ul>
          {{> list}}
        </ul>
      {{/if}}
    </li>
{{/each}
```

### item.js
```Javascript
exports.view = function(req, res){
  var id = res.locals.requestId = req.params.id;  // define `requestId`
  item = {
    _id: 34242424242424,
    title: 'the title',
    text: 'test',
    comments: [
      {
        _id: 111,
        text: 'test111',
        comments: [
          {
            _id: 111.111,
            text: 'test111.111'
          },
          {
            _id: 111.222,
            text: 'test111.222'
          }
        ]
      },
      {
        _id: 222,
        text: 'test222'
      }
    ]
  }

  res.render('item', {
    title: 'test item view',
    item: item,
    comments: item.comments
  });
};
```

**Comment by kidlj** [comment]
UPDATE: 

It doesn't have to be *recursive partials*, we can't use request-level locals in any `{{# each}}` blocks.

**Comment by dougwilson** [comment]
Hi @kidlj sorry this repository has been lingering for a long time. I'm stepping in to lend a hand and go through all the open issues.

So what you are describing is how Handlebars (http://handlebarsjs.com/) works, and not something the `hbs` module is doing. In order to access a value from the above context, Handlebars requires you use `../` to get to the value, for example: `&goto={{ ../requestId }}`

You can find more on the Handlebars website, in the section `Handlebars Paths`. You'll want to open an issue with Handlebars if you're looking to change how the context works in relation to partials, and we can pull in a new version once there is a change there.
