### ISSUE TITLE
partials in {{#each as}}{{/each}} get the wrong context

### ISSUE THREAD

**Issue by kidlj** [pillarjs/hbs#134]

**Comment by dougwilson** [comment]
Hi @kidlj I'm sorry your issue has been sitting here. I have been working to take over this module to get it back into a current state. From what you're describing, it would like a handlebars issue, as this module doesn't do any of the work described in the title.

If you feel otherwise, please feel free to follow up with instructions on how to reproduce the issue you are describing so I can take a look.
