### ISSUE TITLE
Access req data (req.originalUrl) in helpers.

### ISSUE THREAD

**Issue by adyz** [pillarjs/hbs#138]
I am curious how can I have a helper that will do something based on req.originalUrl, but it seems that the req.originalUrl output value is overwritten when multiple requests with different queryparams (?query_test=1+n)

File: **app.js**
```
var hbs = require('hbs');
var app = express();
app.set('view engine', 'hbs');
app.use(function (req, res, next) {
    
    require('./helpers-hbs')(req, res);
    next();

};
```
---

File: **./helpers-hbs** 
```
Handlebars = require('hbs');

module.exports =  function(req, res) {
    
    Handlebars.registerHelper('link', function() {
        return '<a href="#">' + req.originalUrl + '</a>';
    });
    
};
```

**Comment by kothari775** [comment]
hi @adyz  

I am facing same issue right now and looking for work around. I want my custom registered helpers should know request params like req.language, req.hostname etc. which is easily available with middleware. Don't know better way with hbs module.

Is this above one worked with your mutiple hits use case ? de
It would be great if you can share how you overcome with this issue ?

@defunctzombie  @donpark can you help me here somehow ?

Thanks !!

**Comment by dougwilson** [comment]
Hello everyone. Sorry this repository has been lingering for a while. I'm here to try and help out 👍 

The issue with the code in the OP is that every request re-registers a partial locking in the `req` object at the time of registration, which is why OP is seeing the given behavior.

The way to construct this in Handlebars (and ideally any templating engine) is to pass in values that change the rendered output through the locals, and your partials use that as their input to produce the output.

Here is an example:

```js
```
var hbs = require('hbs');
var app = express();
app.set('view engine', 'hbs');

hbs.registerHelper('link', function() {
  return '<a href="#">' + this.originalUrl + '</a>';
});

app.use(function (req, res, next) {
  res.locals.originalUrl = req.originalUrl;
  next()
};
```

I hope this helps! You can find more information about how to create and manage Handlebars helpers at http://handlebarsjs.com/
