### ISSUE TITLE
"The partial header could not be found" only on first run

### ISSUE THREAD

**Issue by rickul** [pillarjs/hbs#148]
I'm getting an error only on the first run:
`The partial header could not be found`

```
const handlebars = require('handlebars');
const hbs = require('hbs').create(handlebars);

hbs.registerPartials(path.resolve(__dirname, '..', 'emails', 'en', 'partials'));
```

The partials directory:
- button.hbs
- footer.hbs
- header.hbs

**Comment by luap** [comment]
Rickul I encountered the same behaviour.  Having looked into it I believe it's caused by the asynchronous nature of finding all the partials on disk.  The first request is processed before the partials have been configured, subsequent requests are therefore fine because expressjs has been setup by then.  The documentation does mention this (see the note at the bottom of Helpers and Partials).  There is a callback from registerPartials which I have used to start the express listening.  Although this seems to work I would welcome other peoples recommendations.

**Comment by NetOperatorWibby** [comment]
@rickul Your code snippet helped me find a solution to a similar problem in a different context. I needed to get Handlebars working with `fastify`'s `point-of-view` module. I may publish this on npm, cleaning up stuff at the moment.

**Comment by iwaduarte** [comment]
Another idea is to wrap the register partials into a promise and only exports the module when the loading ends. Will add some 'delay' when starting your application but it will not break it!

**Comment by dougwilson** [comment]
Hi everyone, I am here to help out with the maintenance of this module and working through the issues and PRs. Looking at the module, it would seem that the original author likely intended you to need to wait for the callback to complete from the register method before trying to actually render anything that needed a partial. I can see where they were coming from, but at the same time, it does feel like a hard to use API. Since all the rendering APIs are already async, what I can do is just add some internal state such that renders are deferred while registration is in progress.
