### ISSUE TITLE
CVE-2021-32822 - Any plans to fix?

### ISSUE THREAD

**Issue by andylincoln** [pillarjs/hbs#201]
Hi there, my team is using this package and we recently received a notification from GitHub's dependabot that there is an open moderate-level vulnerability that has yet to be patched.
[CVE-2021-32822](https://github.com/advisories/GHSA-7f5c-rpf4-86p8).

Are there any plans to remediate the issue?

Thanks!

**Comment by dougwilson** [comment]
Hello, and thank you for bringing this to my attention. Maybe there was some kind of mixup in communications somewhere. I wasn't aware of this before, so will look in to what fixing this would require. If you reach out privately we can work on a fix together, otherwise I will look into a fix. On the surface of the report, it seems the only fix is to remove the layout feature from the module entirely.

**Comment by dougwilson** [comment]
It looks like this affects all the other express handlebars modules as well (ex https://www.npmjs.com/package/express-handlebars). It doesn't seem like there is a public thing about them, so to help out those other modules if they are working on a fix, like I now am, I will remove this report. Hopefully @andylincoln you got an email with my comments you can refer to.
