### ISSUE TITLE
File disclosure vulnerability

### ISSUE THREAD

**Issue by sanjeev9160** [pillarjs/hbs#202]
There is a reported file disclosure vulnerability issue. Details mentioned here: https://github.com/advisories/GHSA-7f5c-rpf4-86p8

Are there any time lines for it to be fixed? 
Thanks.

**Comment by dougwilson** [comment]
Hello, and thank you for opening an issue about this. In the future, please feel free to reach out via email instead of private email. I was not aware of this report until a few days ago, so only just started to look in to it. I also found it affects other express handlebars modules, so I don't want to keep open issues here as it doesn't seem like there is a public report against those modules. If you would like to help work on a fix, please reach out via email @sanjeev9160 with your thoughts on how to fix it.
